### PR TITLE
Update support for Zotero 5

### PR DESCRIPTION
**Pull request by bwiernik**
Trivial upgrade to indicate compatibility with Zotero 5.

### CODE REVIEW

**Comment by bwiernik** [comment]
Because Zotero isn't really any longer a Firefox plugin, I'm not sure whether it makes sense to keep distributing it via the Mozilla website (or whether they will continue to host XUL plugins in the future in any event). I'm happy to keep maintaining the version number compatibility for the plugin on my own GitHub (though I won't be able to do any bug fixes or make more substantive changes).

**Comment by mronkko** [comment]
I will merged the changes in a moment. I think it is better to not fork it because that would mean that there are multiple versions that users can choose from and that can be confusing. I would instead prefer to add you as a contributor to this repository.

I think that distributing through Mozilla website still makes sense because that allows people who use the Firefox plugin will get automatic updates. Distributing through GitHub as well is a good idea.

**Comment by bwiernik** [comment]
That sounds fine. If you could add me as a contributor to this repo, I would appreciate it and it would save some hassle on our parts.

**Comment by bwiernik** [comment]
Thanks!

**Comment by gracile-fr** [comment]
(I think you meant collaborator (i.e. commit access), not contributor which is automatic once you've _contributed_ to a repo.)

**Comment by mronkko** [comment]
Yes, I added bwiernik as a collaborator.

**Pull request merged**
